version: '3.8'

services:
  usenetsync:
    build: .
    container_name: usenetsync
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config:ro
    environment:
      - USENETSYNC_LOG_LEVEL=INFO
      - USENETSYNC_CONFIG_FILE=/app/config/production.json
    ports:
      - "8080:8080"  # If web interface is added
    networks:
      - usenetsync

  monitoring:
    image: prom/prometheus:latest
    container_name: usenetsync-monitoring
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - usenetsync

networks:
  usenetsync:
    driver: bridge

volumes:
  usenetsync_data:
  usenetsync_logs:
