openapi: 3.0.0
info:
  title: UsenetSync API
  description: Complete API for UsenetSync operations with 133 endpoints
  version: 1.0.0
  contact:
    name: UsenetSync Team
    email: support@usenetsync.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.usenetsync.com
    description: Production server

tags:
  - name: System
    description: System and health endpoints
  - name: Security
    description: Security and authentication
  - name: Backup
    description: Backup and recovery
  - name: Monitoring
    description: System monitoring and metrics
  - name: Migration
    description: Database migration
  - name: Publishing
    description: Share publishing and management
  - name: Indexing
    description: File indexing operations
  - name: Upload
    description: Upload operations
  - name: Download
    description: Download operations
  - name: Network
    description: Network management
  - name: Segmentation
    description: File segmentation
  - name: Users
    description: User management
  - name: Folders
    description: Folder management
  - name: Shares
    description: Share management

paths:
  /:
    get:
      tags: [System]
      summary: Get API information
      responses:
        '200':
          description: API information
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  version:
                    type: string
                  status:
                    type: string

  /health:
    get:
      tags: [System]
      summary: Health check
      responses:
        '200':
          description: System health status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  uptime:
                    type: integer
                  database:
                    type: string

  /api/v1/security/generate_user_keys:
    post:
      tags: [Security]
      summary: Generate user key pair
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [user_id]
              properties:
                user_id:
                  type: string
      responses:
        '200':
          description: Keys generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  user_id:
                    type: string
                  public_key:
                    type: string
                  key_type:
                    type: string
                  created_at:
                    type: string
                    format: date-time

  /api/v1/security/hash_password:
    post:
      tags: [Security]
      summary: Hash password securely
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [password]
              properties:
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Password hashed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  hash:
                    type: string
                  salt:
                    type: string
                  message:
                    type: string

  /api/v1/backup/list:
    get:
      tags: [Backup]
      summary: List all backups
      responses:
        '200':
          description: List of backups
          content:
            application/json:
              schema:
                type: object
                properties:
                  backups:
                    type: array
                    items:
                      type: object
                      properties:
                        backup_id:
                          type: string
                        timestamp:
                          type: string
                          format: date-time
                        type:
                          type: string
                        size_bytes:
                          type: integer

  /api/v1/backup/create:
    post:
      tags: [Backup]
      summary: Create system backup
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum: [full, incremental, differential]
                compress:
                  type: boolean
                encrypt:
                  type: boolean
      responses:
        '200':
          description: Backup created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  backup_id:
                    type: string
                  path:
                    type: string
                  size:
                    type: integer
                  checksum:
                    type: string

  /api/v1/monitoring/record_metric:
    post:
      tags: [Monitoring]
      summary: Record custom metric
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, value]
              properties:
                name:
                  type: string
                value:
                  type: number
                type:
                  type: string
                  enum: [gauge, counter, histogram]
      responses:
        '200':
          description: Metric recorded
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string

  /api/v1/folders:
    get:
      tags: [Folders]
      summary: Get all folders
      responses:
        '200':
          description: List of folders
          content:
            application/json:
              schema:
                type: object
                properties:
                  folders:
                    type: array
                    items:
                      type: object
                      properties:
                        folder_id:
                          type: string
                        path:
                          type: string
                        name:
                          type: string
                        status:
                          type: string
                        file_count:
                          type: integer
                        total_size:
                          type: integer
                        created_at:
                          type: string
                          format: date-time

  /api/v1/add_folder:
    post:
      tags: [Folders]
      summary: Add a new folder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [path]
              properties:
                path:
                  type: string
      responses:
        '200':
          description: Folder added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  folder_id:
                    type: string
                  path:
                    type: string
                  message:
                    type: string

  /api/v1/shares:
    get:
      tags: [Shares]
      summary: Get all shares
      responses:
        '200':
          description: List of shares
          content:
            application/json:
              schema:
                type: object
                properties:
                  shares:
                    type: array
                    items:
                      type: object
                      properties:
                        share_id:
                          type: string
                        folder_id:
                          type: string
                        access_level:
                          type: string
                        download_count:
                          type: integer
                        created_at:
                          type: string
                          format: date-time

  /api/v1/create_share:
    post:
      tags: [Shares]
      summary: Create a share
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [folder_id]
              properties:
                folder_id:
                  type: string
                access_level:
                  type: string
                  enum: [public, private, protected]
                password:
                  type: string
      responses:
        '200':
          description: Share created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  share_id:
                    type: string
                  url:
                    type: string

  /api/v1/upload/strategy:
    get:
      tags: [Upload]
      summary: Get optimal upload strategy
      parameters:
        - name: file_size
          in: query
          schema:
            type: integer
        - name: file_type
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Upload strategy
          content:
            application/json:
              schema:
                type: object
                properties:
                  strategy:
                    type: string
                    enum: [direct, chunked, streaming]
                  chunk_size:
                    type: integer

  /api/v1/download/cache/stats:
    get:
      tags: [Download]
      summary: Get cache statistics
      responses:
        '200':
          description: Cache statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  size_mb:
                    type: number
                  files:
                    type: integer
                  hits:
                    type: integer
                  misses:
                    type: integer

  /api/v1/network/connection_pool/stats:
    get:
      tags: [Network]
      summary: Get connection pool statistics
      responses:
        '200':
          description: Connection pool stats
          content:
            application/json:
              schema:
                type: object
                properties:
                  active:
                    type: integer
                  idle:
                    type: integer
                  total:
                    type: integer
                  max:
                    type: integer

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        detail:
          type: string
        status_code:
          type: integer
      required:
        - detail

    Success:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
      required:
        - success

    ProgressInfo:
      type: object
      properties:
        operation:
          type: string
        total:
          type: integer
        current:
          type: integer
        percentage:
          type: number
        status:
          type: string
        message:
          type: string

security:
  - ApiKeyAuth: []
  - BearerAuth: []