package com.yourapp;

import com.wyday.turboactivate.*;
import javax.swing.JOptionPane;


public class PKey extends javax.swing.JDialog {

	/** A return status code - returned if Cancel button has been pressed */
	public static final int RET_CANCEL = 0;
	/** A return status code - returned if OK button has been pressed */
	public static final int RET_OK = 1;

	private TurboActivate ta;

	private int returnStatus = RET_CANCEL;


	/**
	 * Creates new form PKey
	 */
	public PKey(java.awt.Frame parent, boolean modal, TurboActivate ta) {
		super(parent, modal);
		initComponents();

		this.ta = ta;

		try
		{
			// get the existing product key
			if (ta.IsProductKeyValid())
				txtPKey.setText(ta.GetPKey());
		}
		catch (Exception ex) { }
	}

	private void doClose(int retStatus)
	{
		returnStatus = retStatus;
		setVisible(false);
		dispose();
	}

	/** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
	public int getReturnStatus()
	{
		return returnStatus;
	}


	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMsg = new javax.swing.JLabel();
        txtPKey = new javax.swing.JTextField();
        btnActivate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Activate now");
        setResizable(false);

        lblMsg.setText("Enter your product key and click activate:");

        btnActivate.setText("Activate");
        btnActivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivate_Click(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel_Click(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPKey, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnActivate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMsg)
                .addGap(18, 18, 18)
                .addComponent(txtPKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnActivate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancel_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel_Click
		doClose(RET_CANCEL);
    }//GEN-LAST:event_btnCancel_Click

    private void btnActivate_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivate_Click
		try
		{
			boolean existingKey = ta.IsProductKeyValid();
			if ((existingKey && !ta.GetPKey().equals(txtPKey.getText())) || !existingKey)
			{
				// save the new key
				if (!ta.CheckAndSavePKey(txtPKey.getText(), TurboActivate.TA_SYSTEM))
					throw new Exception("The product key is not valid.");
			}

			// try to activate and close the form
			ta.Activate();
			doClose(RET_OK);
		}
		catch (Exception ex)
		{
			JOptionPane.showMessageDialog(null, "Activation failed: " + ex.getMessage(), "Activation failed", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_btnActivate_Click

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivate;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JTextField txtPKey;
    // End of variables declaration//GEN-END:variables
}
