package com.yourapp;

import com.wyday.turboactivate.*;
import javax.swing.JOptionPane;


public class ReVerifyNow extends javax.swing.JDialog {

	/** A return status code - returned if Cancel button has been pressed */
	public static final int RET_CANCEL = 0;
	/** A return status code - returned if OK button has been pressed */
	public static final int RET_OK = 1;

	private TurboActivate ta;
	private boolean inGrace = false;
	public int GenuineDaysLeft;
	public boolean noLongerActivated = false;

	private int returnStatus = RET_CANCEL;


	/**
	 * Creates new form ReVerifyNow
	 */
	public ReVerifyNow(java.awt.Frame parent, boolean modal, TurboActivate ta, int DaysBetweenChecks, int GracePeriodLength) {
		super(parent, modal);
		initComponents();

		this.ta = ta;

		BoolRef inGraceRef = new BoolRef();

		try
		{
			// Use the days between checks and grace period from
			// the main form
			GenuineDaysLeft = ta.GenuineDays(DaysBetweenChecks, GracePeriodLength, inGraceRef);

			inGrace = inGraceRef.getValue();
		}
		catch (Exception ex) { }

		if (GenuineDaysLeft == 0)
			lblDescr.setText("You must re-verify with the activation servers to continue using this app.");
		else
			lblDescr.setText("You have " + GenuineDaysLeft +  " days to re-verify with the activation servers.");
	}

	private void doClose(int retStatus)
	{
		returnStatus = retStatus;
		setVisible(false);
		dispose();
	}

	/** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
	public int getReturnStatus()
	{
		return returnStatus;
	}


	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDescr = new javax.swing.JLabel();
        btnReverify = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Re-verify with the activation servers");
        setResizable(false);

        lblDescr.setText("You have X days to re-verify with the activation servers.");

        btnReverify.setText("Re-verify now");
        btnReverify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReverify_Click(evt);
            }
        });

        btnExit.setText("Exit application");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit_Click(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDescr)
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReverify)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDescr)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReverify)
                    .addComponent(btnExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReverify_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReverify_Click
		try
		{
			switch (ta.IsGenuine())
			{
				case Genuine:
				case GenuineFeaturesChanged:

					doClose(RET_OK);
					break;

				case NotGenuine:
				case NotGenuineInVM:

					noLongerActivated = true;
					doClose(RET_CANCEL);
					break;

				case InternetError:
					JOptionPane.showMessageDialog(null, "Failed to connect with the activation servers.", "Failed to re-verify", JOptionPane.ERROR_MESSAGE);
					break;
			}
		}
		catch (Exception ex)
		{
			JOptionPane.showMessageDialog(null, "Failed to re-verify with the activation servers. Full error: " + ex.getMessage(), "Failed to re-verify", JOptionPane.ERROR_MESSAGE);
			btnReverify.requestFocus();
		}
    }//GEN-LAST:event_btnReverify_Click

    private void btnExit_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit_Click
		doClose(RET_CANCEL);
    }//GEN-LAST:event_btnExit_Click


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReverify;
    private javax.swing.JLabel lblDescr;
    // End of variables declaration//GEN-END:variables
}
