package com.yourapp;

import com.wyday.turboactivate.*;
import javax.swing.JOptionPane;


public class TrialExtension extends javax.swing.JDialog {

	/** A return status code - returned if Cancel button has been pressed */
	public static final int RET_CANCEL = 0;
	/** A return status code - returned if OK button has been pressed */
	public static final int RET_OK = 1;

	private TurboActivate ta;
	private int trialFlags = 0;

	private int returnStatus = RET_CANCEL;


	/**
	 * Creates new form TrialExtension
	 */
	public TrialExtension(java.awt.Frame parent, boolean modal, TurboActivate ta, int useTrialFlags) {
		super(parent, modal);
		initComponents();

		this.ta = ta;
		this.trialFlags = useTrialFlags;
	}

	private void doClose(int retStatus)
	{
		returnStatus = retStatus;
		setVisible(false);
		dispose();
	}

	/** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
	public int getReturnStatus()
	{
		return returnStatus;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMsg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtExtension = new javax.swing.JTextArea();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Trial extension");
        setResizable(false);

        lblMsg.setText("Paste your trial extension here:");

        txtExtension.setColumns(20);
        txtExtension.setRows(5);
        jScrollPane1.setViewportView(txtExtension);

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOK_Click(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel_Click(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMsg)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnCancel))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOK_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOK_Click
		try
		{
			// try to extend the trial and close the form
			ta.ExtendTrial(txtExtension.getText(), trialFlags);
			doClose(RET_OK);
		}
		catch (Exception ex)
		{
			JOptionPane.showMessageDialog(null, "Trial extension failed: " + ex.getMessage(), "Trial extension failed", JOptionPane.ERROR_MESSAGE);
			txtExtension.requestFocus();
		}
    }//GEN-LAST:event_btnOK_Click

    private void btnCancel_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel_Click
		doClose(RET_CANCEL);
    }//GEN-LAST:event_btnCancel_Click


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JTextArea txtExtension;
    // End of variables declaration//GEN-END:variables
}
