name: Security Vulnerability
description: Report a security vulnerability (private issue)
title: "[SECURITY] "
labels: ["security", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        WARNING: Please do not report security vulnerabilities in public issues.
        Instead, please report them to security@usenetsync.dev or use GitHub's private vulnerability reporting.

  - type: textarea
    id: vulnerability
    attributes:
      label: Vulnerability Description
      description: Describe the security vulnerability
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
