name: Dependency Update

on:
  schedule:
    - cron: '0 6 * * 1'  # Weekly on Monday at 6 AM

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Update dependencies
      run: |
        pip install --upgrade pip
        pip list --outdated --format=json > outdated.json
    
    - name: Create PR for dependency updates
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'deps: Update Python dependencies'
        title: 'Update Python dependencies'
        body: 'Automated dependency update'
        branch: update-dependencies
